### ISSUE TITLE
--font-size-px is returned as pixel value, breaks calc in mode: 'modern'

### ISSUE THREAD

**Issue by essejmclean** [stormwarning/tailwindcss-capsize#129]
The `--font-size-px` CSS custom property gets returned after being run through TailwindCSS's internals as a pixel value.

This creates an issue with the various CSS `calc`s that use the `--font-size-px` CSS custom property since certain units cannot be mixed (addition `+` and subtraction `-` in this use case).

This happens because the `fontSizeActual` variable in the `plugin.ts` file is passed as a `number` and `postcss-js` (which TailwindCSS uses under the hood to parse plugins) converts this to a pixel value as is common behaviour with most CSS-in-JS solutions.

I've created a pull request (#128) that solves this issue by wrapping `fontSizeActual` with `String()` and edited the tests to check that the values for `--font-size-px` are truly flat values (i.e. `--font-size-px: 16;`, not `--font-size-px: 16px;`).

Separately I want to thank @stormwarning for releasing v3.0.0 - this update has vastly improved the size of my CSS files when working with themes that utilize many font sizes and line heights.

**Comment by stormwarning** [comment]
Thanks for catching the issue and submitting a fix too! 🙌 

> this update has vastly improved the size of my CSS files when working with themes that utilize many font sizes and line heights

Glad to hear it! I'm just happy someone else besides me finds the plugin useful 😄

**Comment by stormwarning** [comment]
Fixed in #128
