### ISSUE TITLE
Precision loss

### ISSUE THREAD

**Issue by andriytyurnikov** [stormwarning/tailwindcss-capsize#177]
https://github.com/stormwarning/tailwindcss-capsize/blob/e803b6fa02e43257d974c94a4558936f73ccc033/src/utils.ts#L25

When font-size is set in fractions of pixels, precision loss happens in `normaliseValue` function, which enforces integers on px values via usage of `parseInt`. Therefore value of `actualPixels` is always with loss of precision.

**Comment by stormwarning** [comment]
Fixed in #178 and released in v3.0.3 👍
