### ISSUE TITLE
Missing TypeScript Types

### ISSUE THREAD

**Issue by igl** [stormwarning/tailwindcss-capsize#213]
I recently switch to having a `tailwind.config.ts` (because you can) and i noticed that this plugin throws an error because types are not correctly generated:

<img width="719" alt="image" src="https://github.com/stormwarning/tailwindcss-capsize/assets/293519/bc6bf636-1cd0-4924-a63a-2fd609fc4aaa">

The `index.d.ts` generated as the main type location specified by the package.json lacks any type definitions.

**Comment by stormwarning** [comment]
Oh interesting, I'll see what I can do about that 👍 Is the plugin still working if you ignore the TS error? Just want to be sure it's just missing types and not something with how it's being exported or anything.

**Comment by igl** [comment]
The plugin works, but i mute the typescript error with `plugins: [capsize as any]`or @ts-ignore-next-line also works
